# Generated by Django 4.2.7 on 2023-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('medida', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('cantidad_en_stock', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
