# Generated by Django 4.2.7 on 2023-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_producto_color_producto_color_luz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_luz',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_sable',
            field=models.CharField(max_length=50),
        ),
    ]
