# Generated by Django 4.2.7 on 2023-11-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad_en_stock',
            new_name='stock',
        ),
    ]
