# Generated by Django 4.2.7 on 2023-11-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_transaccion_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='precio_total',
            field=models.FloatField(),
        ),
    ]
